### ISSUE TITLE
What are the versions of Slurm and PySlurm?

### ISSUE THREAD

**Issue by wooloo1121** [mac133k/yaspex#2]
Hi,

We would like to utilize your exporter on our cluster, but found that the req metrics did not work. We think it might be due to the versions of slurm or pyslurm not compatible. May I ask what the versions of slurm and pyslurm are on which this exporter was tested?

Thank you very much and look forward to your reply!

Best,
Karin

**Comment by mac133k** [comment]
Hi Karin,

Yaspex was tested with Slurm v19 and v20. If you are unable to fetch the information about requested resources it could be due to permissions, ie. some cluster data are only available if the query command is run by the root user. You can verify that by running some diagnostics commands like sinfo, sacct, on the cluster monitoring host as different users (ie. regular user, slurm daemon user and root) and see if there any differences in the output. If that does not give you any clues let me know and I'll help you to investigate further.

**Comment by wooloo1121** [comment]
Thank you!
